/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.5.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.npmanos.tbalib.model


/**
 * 
 * @param districtCmp `true` if this event is a District Championship event.
 * @param total Total points awarded at this event.
 * @param alliancePoints Points awarded for alliance selection.
 * @param elimPoints Points awarded for elimination match performance.
 * @param awardPoints Points awarded for event awards.
 * @param eventKey TBA Event key for this event.
 * @param qualPoints Points awarded for qualification match performance.
 */

data class DistrictRankingEventPoints (
    /* `true` if this event is a District Championship event. */
    val districtCmp: kotlin.Boolean,
    /* Total points awarded at this event. */
    val total: kotlin.Int,
    /* Points awarded for alliance selection. */
    val alliancePoints: kotlin.Int,
    /* Points awarded for elimination match performance. */
    val elimPoints: kotlin.Int,
    /* Points awarded for event awards. */
    val awardPoints: kotlin.Int,
    /* TBA Event key for this event. */
    val eventKey: kotlin.String,
    /* Points awarded for qualification match performance. */
    val qualPoints: kotlin.Int
) 



