/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.5.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.npmanos.tbalib.model


/**
 * 
 * @param autoPoints 
 * @param teleopPoints 
 * @param containerPoints 
 * @param totePoints 
 * @param litterPoints 
 * @param foulPoints 
 * @param adjustPoints 
 * @param totalPoints 
 * @param foulCount 
 * @param toteCountFar 
 * @param toteCountNear 
 * @param toteSet 
 * @param toteStack 
 * @param containerCountLevel1 
 * @param containerCountLevel2 
 * @param containerCountLevel3 
 * @param containerCountLevel4 
 * @param containerCountLevel5 
 * @param containerCountLevel6 
 * @param containerSet 
 * @param litterCountContainer 
 * @param litterCountLandfill 
 * @param litterCountUnprocessed 
 * @param robotSet 
 */

data class MatchScoreBreakdown2015Alliance (
    val autoPoints: kotlin.Int? = null,
    val teleopPoints: kotlin.Int? = null,
    val containerPoints: kotlin.Int? = null,
    val totePoints: kotlin.Int? = null,
    val litterPoints: kotlin.Int? = null,
    val foulPoints: kotlin.Int? = null,
    val adjustPoints: kotlin.Int? = null,
    val totalPoints: kotlin.Int? = null,
    val foulCount: kotlin.Int? = null,
    val toteCountFar: kotlin.Int? = null,
    val toteCountNear: kotlin.Int? = null,
    val toteSet: kotlin.Boolean? = null,
    val toteStack: kotlin.Boolean? = null,
    val containerCountLevel1: kotlin.Int? = null,
    val containerCountLevel2: kotlin.Int? = null,
    val containerCountLevel3: kotlin.Int? = null,
    val containerCountLevel4: kotlin.Int? = null,
    val containerCountLevel5: kotlin.Int? = null,
    val containerCountLevel6: kotlin.Int? = null,
    val containerSet: kotlin.Boolean? = null,
    val litterCountContainer: kotlin.Int? = null,
    val litterCountLandfill: kotlin.Int? = null,
    val litterCountUnprocessed: kotlin.Int? = null,
    val robotSet: kotlin.Boolean? = null
) 



