/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.5.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.npmanos.tbalib.model


/**
 * The `Media` object contains a reference for most any media associated with a team or event on TBA.
 * @param type String type of the media element.
 * @param foreignKey The key used to identify this media on the media site.
 * @param details If required, a JSON dict of additional media information.
 * @param preferred True if the media is of high quality.
 * @param directUrl Direct URL to the media.
 * @param viewUrl The URL that leads to the full web page for the media, if one exists.
 */

data class Media (
    /* String type of the media element. */
    val type: Media.Type,
    /* The key used to identify this media on the media site. */
    val foreignKey: kotlin.String,
    /* If required, a JSON dict of additional media information. */
    val details: kotlin.Any? = null,
    /* True if the media is of high quality. */
    val preferred: kotlin.Boolean? = null,
    /* Direct URL to the media. */
    val directUrl: kotlin.String? = null,
    /* The URL that leads to the full web page for the media, if one exists. */
    val viewUrl: kotlin.String? = null
) 


{
    /**
    * String type of the media element.
    * Values: youtube,cdphotothread,imgur,facebookProfile,youtubeChannel,twitterProfile,githubProfile,instagramProfile,periscopeProfile,grabcad,instagramImage,externalLink,avatar
    */

    enum class Type(val value: kotlin.String)
}

