/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.5.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.npmanos.tbalib.model

/**
 * Playoff status for this team, may be null if the team did not make playoffs, or playoffs have not begun.
 * @param level The highest playoff level the team reached.
 * @param currentLevelRecord 
 * @param record 
 * @param status Current competition status for the playoffs.
 * @param playoffAverage The average match score during playoffs. Year specific. May be null if not relevant for a given year.
 */

data class TeamEventStatusPlayoff (
    /* The highest playoff level the team reached. */
    val level: TeamEventStatusPlayoff.Level? = null,
    val currentLevelRecord: WLTRecord? = null,
    val record: WLTRecord? = null,
    /* Current competition status for the playoffs. */
    val status: TeamEventStatusPlayoff.Status? = null,
    /* The average match score during playoffs. Year specific. May be null if not relevant for a given year. */
    val playoffAverage: kotlin.Int? = null
) 


{
    /**
    * The highest playoff level the team reached.
    * Values: qm,ef,qf,sf,f
    */

    enum class Level(val value: kotlin.String)

    /**
    * Current competition status for the playoffs.
    * Values: won,eliminated,playing
    */

    enum class Status(val value: kotlin.String)
}

