/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.5.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.npmanos.tbalib.model


/**
 * 
 * @param key TBA team key with the format `frcXXXX` with `XXXX` representing the team number.
 * @param teamNumber Official team number issued by FIRST.
 * @param name Official long name registered with FIRST.
 * @param nickname Team nickname provided by FIRST.
 * @param city City of team derived from parsing the address registered with FIRST.
 * @param stateProv State of team derived from parsing the address registered with FIRST.
 * @param country Country of team derived from parsing the address registered with FIRST.
 */

data class TeamSimple (
    /* TBA team key with the format `frcXXXX` with `XXXX` representing the team number. */
    val key: kotlin.String,
    /* Official team number issued by FIRST. */
    val teamNumber: kotlin.Int,
    /* Official long name registered with FIRST. */
    val name: kotlin.String,
    /* Team nickname provided by FIRST. */
    val nickname: kotlin.String? = null,
    /* City of team derived from parsing the address registered with FIRST. */
    val city: kotlin.String? = null,
    /* State of team derived from parsing the address registered with FIRST. */
    val stateProv: kotlin.String? = null,
    /* Country of team derived from parsing the address registered with FIRST. */
    val country: kotlin.String? = null
) 



